(function (translator) {
	translator.translations["hr"] = {
		// javascript alerts or messages
		"testneteditionactivated": "TESTNET aktivan",
		"paperlabelbitcoinaddress": "Bitcoin adresa: ",
		"paperlabelprivatekey": "Privatni ključ:",
		"paperlabelencryptedkey": "Enkriptirani privatni ključ (Zahtjeva lozinku)",
		"bulkgeneratingaddresses": "Adresa se generira... ",
		"brainalertpassphrasetooshort": "Lozinka koju ste odabrali je prekratka.\n\n",
		"brainalertpassphrasewarning": "Oprez: Odabir kompliciranog pristupnog izraza (passphrase-a) je vrlo bitno, kako bi izbjegli mogućnost lakog probijanja šifre putem brute-force metode i moguće izgubili svoje bitcoine.",
		"brainalertpassphrasedoesnotmatch": "Uneseni pristupni izrazi (passphrase-i) se ne poklapaju.",
		"detailalertnotvalidprivatekey": "Uneseni tekst nije ispravan privatni ključ",
		"detailconfirmsha256": "Uneseni tekst nije ispravan privatni ključ!\n\nDa li bi željeli uneseni tekst koristiti kao pristupni izraz (passphrase) i kreirati privatni ključ koristeći SHA256 hash od pristupnog izraza (passphrase-a)?\n\nOprez: Odabir kompliciranog pristupnog izraza (passphrase-a) je vrlo bitno, kako bi izbjegli mogućnost lakog probijanja šifre putem brute-force metode i moguće izgubili svoje bitcoine.",
		"detailbip38decryptbutton": "Dekriptiraj BIP38",
		"detailbip38encryptbutton": "Enkriptiraj BIP38",
		"bip38alertincorrectpassphrase": "Neispravan pristupni izraz (passphrase) za navedeni enkriptirani privatni ključ.",
		"bip38alertpassphraserequired": "Pristupni izraz je potreban za BIP38 ključ",
		"vanityinvalidinputcouldnotcombinekeys": "Neispravan unos. Nemoguće je spojiti ključeve.",
		"vanityalertinvalidinputpublickeysmatch": "Neispravan unos. Javni ključevi oba unosa se poklapaju. Potrebno je unesti dva različita ključa.",
		"vanityalertinvalidinputcannotmultiple": "Neispravan unos. Nemoguće je uvišestručiti navedena dva javna ključa. Odaberite 'Dodaj' za dodavanje dva javana ključa kako bi dobili bitcoin adresu.",
		"vanityprivatekeyonlyavailable": "Dostupno samo kada spajate dva privatna ključa",
		"vanityalertinvalidinputprivatekeysmatch": "Neispravan unos. Privatni ključevi se podudaraju. Potrebno je unesti dva različita ključa.",

		// header and menu html
		"tagline": "Open Source generator Bitcoin novčanika napisan u JavaScriptu koji se izvršava samo u web pregledniku",
		"generatelabelbitcoinaddress": "Generiranje Bitcoin adrese",
		"generatelabelmovemouse": "Pomičite kursor miša po ekranu kako bi dodali više entropije i prizvoljnih podataka...",
		"generatelabelkeypress": "ILI napišite neke prizvoljne znakove u ovo polje",
		"singlewallet": "Jedan novčanik",
		"paperwallet": "Papirnati novčanik",
		"bulkwallet": "Nekoliko novčanika odjednom (bulk wallet)",
		"brainwallet": "Novčanik zaštićen lozinkom (passwordom)",
		"vanitywallet": "Vanity adresa",
		"splitwallet": "Podijeli novčanik",
		"detailwallet": "Detalji novčanika",

		// footer html
		"footerlabeldonations": "Donacije:",
		"footerlabeltranslatedby": "Prijevod: 1DGX4Zu83i3zL3zCNRaiat6tbtPMgEyhNE",
		"footerlabelpgp": "PGP",
		"footerlabelversion": "Povijest verzija",
		"footerlabelgithub": "GitHub Repozitorij",
		"footerlabelgithubzip": "zip",
		"footerlabelsig": "sig",
		"footerlabelcopyright1": "Copyright bitaddress.org.",
		"footerlabelcopyright2": "Copyright JavaScripta je uključen u kódu.",
		"footerlabelnowarranty": "Bez garancije.",

		// status html
		"statuslabelcryptogood": "&#10004; OK!", 
		"statuslabelcryptogood1": "VAš web preglednik može generirati kritografske nasumične ključeve koristeći window.crypto.getRandomValues", 
		"statusokcryptogood": "OK", 
		"statuslabelcryptobad": "&times; Oh ne!", 
		"statuslabelcryptobad1": "Vaš web preglednik ne podržava window.crypto.getRandomValues. Preporučujemo upotrebu modernijeg web preglednika s ovim generatorom kako bi uvećali sigurnost generiranih ključeva.",
		"statusokcryptobad": "OK", 
		"statuslabelunittestsgood": "&#10004; OK!",
		"statuslabelunittestsgood1": "Svi sinkroni jedinični testovi prolaze.",
		"statusokunittestsgood": "OK", 
		"statuslabelunittestsbad": "&times; Oh ne!",
		"statuslabelunittestsbad1": "Neki sinkroni jedinični testovi nisu prošli. Preporučujemo upotrebu nekog modernije web preglednika s ovim generatorom.",
		"statusokunittestsbad": "OK",
		"statuslabelprotocolgood": "&#10004; OK!",
		"statuslabelprotocolgood1": "Pokrećete ovaj generator sa svog lokalnog računala. <br />Savjet: Ponovo provjerite da li sigurno pokrećete lokalnu verziju ",
		"statusokprotocolgood": "OK",
		"statuslabelprotocolbad": "&#9888; Dobro razmislite!",
		"statuslabelprotocolbad1": "Čini se kao da pokrećete ovaj generator s web stranice na internetu. Za novčanike u kojima će te držati vrijednosti preporučamo",
		"statuslabelprotocolbad2": "preuzmite",
		"statuslabelprotocolbad3": ".zip datoteku s GitHub-a i pokrenite ovaj generator lokalno s vašeg računala kao lokalnu .html datoteku.",
		"statusokprotocolbad": "OK",
		"statuslabelkeypool1": "Ovo je popis svih Bitcoin adresa i privatnih ključeva koje ste generirali tokom trenutne sesije. Ponovno učitavanje/osvježavanje stranice će kreirati novu sesiju.", 
		"statuskeypoolrefresh": "Osvježi",
		"statusokkeypool": "OK",

		// single wallet html
		"newaddress": "Generiraj novu adresu",
		"singleprint": "Ispis",
		"singlelabelbitcoinaddress": "Bitcoin adresa",
		"singlelabelprivatekey": "Privatni ključ (WIF &ndash; Format prilagođen za uvoz/import):",
		"singletip1": "<b>Bitcoin novčanik</b> je jednostavni par javne adrese sa pridruženim privatnim ključem. Takav novčanik je generiran u vašem web pregledniku i prikazan je gore.",
		"singletip2": "<b>Kako bi zaštitili vaš novčanik</b> ispišite ili spremite na neki drugi način Bitcoin adresu i pripadajući privatni ključ. Vrlo je važno da napravite sigurnosnu kopiju vašeg privatnog ključa i pohranite je na neko sigurno mjesto. Ova web stranica nema nikakve podatke o vašem ključu. Ako ste upoznati s PGP tehnologijom, možete preuzeti ovu HTML stranicu (sažetu u jedan .html file) i provjeriti da posjedujete autentičnu verziju izdanu od autora ove web stranice, provjeravajući SHA256 hash ovog .html dokumenta sa SHA256 hashom dostupnim u potpisanoj verziji povijesnog dokumenta u podnožju stranice. \nUkoliko napustite/osvježite stranicu ili kliknete na 'Generiraj novu adresu', generirat će se novi privatni ključ s nemogućnošću vraćanja na prijašnji. Vaš privatni ključ bitcoin adrese bi trebali čuvati tajnim. Ukoliko s nekim podijelite privatni ključ, ta osoba ima pristup slanju svih sredstava iz vašeg bitcoin novčanika. Ukoliko ispišete vaš novčanik na papir, pospremite ga u vodonepropusnu vrečicu kako bi ga zaštitili od vlage. Postupajte s papirnatim bitcoin novčanikom kao s gotovinom.",
		"singletip3": "<b>Dodajte sredstva</b> u vaš novčanik tako da vam drugi pošalju bitcoine na vašu adresu.",
		"singletip4": "<b>Provjerite iznos sredstava u novčaniku</b> na web stranicama <a href=\"https://blockchain.info\">blockchain.info</a> ili <a href=\"https://blockexplorer.com\">blockexplorer.com</a> upisujući svoju bitcoin adresu.",
		"singletip5": "<b>Želite potrošiti bitcoine?</b> Na web stranici <a href=\"https://blockchain.info\">blockchain.info</a> možete prebaciti sva sredstva sa svoje adrese na račun koji ste kreirali na njihovoj stranici. Drugi način je preuzimanje nekog bitcoin p2p klijenta i uvoz svojih privatnih ključeva u novčanik p2p klijenta. Imajte na umu da kada uvezete svoj privatni ključ u p2p klijent i potršite sredstva s računa, vaš ključ će biti sažet s drugim privatnim ključevima u novčaniku p2p klijenta. Kada napravite transakciju, povrat preostale svote bitcoina će biti prebačen na drugu bitcoin adresu unutar p2p klijenta. Tada morate napraviti sigurnosnu kopiju novčanika p2p klijenta i pohraniti ga na sigurno jer su tada vaši preostali bitcoini na toj adresi. Satoshi je savjetovao da nikada ne brišete jednom napravljeni novčanik.",
		"singleshare": "PODIJELITE",
		"singlesecret": "SAKRIJTE",

		// paper wallet html
		"paperlabelhideart": "Sakrij grafiku?",
		"paperlabeladdressesperpage": "Broj adresa po stranici",
		"paperlabeladdressestogenerate": "Broj adresa za generirati:",
		"papergenerate": "Generiraj",
		"paperprint": "Ispis",
		"paperlabelBIPpassphrase": "Pristupni izraz (passphrase):",
		"paperlabelencrypt": "BIP38?",

		// bulk wallet html
		"bulklabelstartindex": "Početni redni broj:",
		"bulklabelrowstogenerate": "Broj adresa za generiranje:",
		"bulklabelcompressed": "Kompresije?",
		"bulkgenerate": "Generiraj",
		"bulkprint": "Ispis",
		"bulklabelcsv": "CSV format zapisa adresa:",
		"bulklabelBIPpassphrase": "Pristupni izraz (passphrase):",
		"bulklabelformat": "Redni broj, Adresa, Privatni ključ (WIF &ndash; Format prilagođen za uvoz/import novčanika)",
		"bulklabelq1": "Zašto koristiti Nekoliko novčanika odjednom (bulk wallet) za primanje bitcoina na mojoj stranici?",
		"bulka1": "Tradicionalni način primanja bitcoina na stranici je instalacija bitcoind servisa na server. Mnogi pružatelji usluga hostinga ne podržavaju instalaciju bitcoind servisa. Takodjer, takvim pristupom ostavljate privatne ključeve na serveru riskirajući da netko dođeu posjed vaših ključeva provalom na server. Kada koristite Nekoliko novčanika odjednom (bulk wallet) na server je potrebno kopirati samo bitcoin adrese bez privatnih ključeva. Tada možete biti sigurniji da čak i ako netko provali na web server, ne može do vaših novčanika pošto ne posjeduje privatne ključeve.",
		"bulklabelq2": "Kako koristiti Nekoliko novčanika odjednom (bulk wallet) za primanje bitcoina na stranici?",
		"bulklabela2li1": "Koristite Nekoliko novčanika odjednom (bulk wallet) za pregeneriranje ve'eg broja bitcoin adresa (10,000+). Kopirajte CSV formatiranu listu u sigurnu datoteku na vašem računalu. Pohranite sigurnosnu kopiju datoteke dodatno i na neku drugu sigurnu lokaciju.",
		"bulklabela2li2": "Nakon sto šte pohranili sigurnosne kopije generiranih adresa i privatnih ključeva pripremite CSV datoteku za uvoz na server tako da uklonite unose privatnih ključeva iz CSV liste i uvezete samo redne brojeve i bitcoin adrese u tablicu baze na serveru. (Budite sigurni da ne unesete u bazu privatne ključeve generiranih bitcoin novčanika, u suprotnom riskirate gubitak privatnih ključeva u slučaju provale na web server. U bazu uvozite CSV samo s unosima bitcoin adresa jer će one biti prikazane korisnicima.).",
		"bulklabela2li3": "Dodajte opciju za plaćanje bitcoinima u košarici na vašoj web stranici. Kada korisnik odabere plaćanje u bitcoinima, tada će mu se prikazati jedna od adresa uvezenih na server iz CSV liste kao adresa na koju radi uplatu i spremiti je pod njegovu narudžbu iz košarice.",
		"bulklabela2li4": "Sada možete postaviti obavijesti o pristiglim uplatama. Na internetu možete potražiti 'bitcoin payment notification' i učlaniti se na neki od ponuđenih usluga za obavještavanje o bitcoin uplatama. Postoje mnogi servisi koji će vas obavijestiti putem web usluga, APIa, SMS poruka, email poruka i sl. Kada primite obavijest, koja može biti programirana za automatizaciju, možete obraditi korisnikovu narudžbu. Ako želite ručno provjeriti uplatu, možete koristiti <a href=\"https://www.blockexplorer.com\">Block Explorer</a>. Zamijenite VAŠABITCOINADRESA s bitcoin adresom koju provjeravate. Može proći od 10 minuta do sat vremena dok transakcija ne bude potvrđena na mreži, ovisno o stanju mreže. http://www.blockexplorer.com/address/VAŠABITCOINADRESA \n\nNepotvrđene transakcije možete provjeriti na  <a href=\"https://blockchain.info\">blockchain.info</a> Transakcija bi se tamo trebala prikazati unutar 30 sekundi.",
		"bulklabela2li5": "Količina bitcoina će se uvećavati s uplatama. Koristite originalni novčanik kreiran u koraku 1 kako bi ih potrošili.",

		// brain wallet html
		"brainlabelenterpassphrase": "Unesite pristupni izraz (passphrase):",
		"brainlabelshow": "Prikaži?",
		"brainprint": "Ispis",
		"brainlabelconfirm": "Potvrdi pristupni izraz (passphrase):",
		"brainview": "Prikaži",
		"brainalgorithm": "Algoritam: SHA256 (pristupni izraz)",
		"brainlabelbitcoinaddress": "Bitcoin adresa:",
		"brainlabelprivatekey": "Privatni ključ (WIF &ndash; format prilagođen za uvoz/import):",
		"brainlabelcompressed": "Kompresija adrese?",

		// vanity wallet html
		"vanitylabelstep1": "Korak 1 &ndash; Generirajte par ključeva za prvi korak",
		"vanitynewkeypair": "Generiraj",
		"vanitylabelstep1publickey": "Javni ključ Koraka 1",
		"vanitylabelstep1pubnotes": "Kopirajte gornji javni ključ u polje Your-Part-Public-Key na Vanity Pool stranici.",
		"vanitylabelstep1privatekey": "Privatni ključ Koraka 1",
		"vanitylabelstep1privnotes": "Kopirajte gornji privatni ključ u tekstualnu datoteku i pohranite je na sigurnu lokaciju, najsigurnije na enkriptirani disk. Ova će vam informacija biti potrebna za dohvat privatnog ključa kada Vanity Pool pronađe vaš željeni prefiks.",
		"vanitylabelstep2calculateyourvanitywallet": "Korak 2 &ndash; Izračunaj Vanity novčanik",
		"vanitylabelenteryourpart": "Unesite generirani privatni ključ iz Koraka 1:",
		"vanitylabelenteryourpoolpart": "Unesite privatni ključ s Vanity Pool novčanika (Pool Part Private Key):",
		"vanitylabelnote1": "[NAPOMENA: ovo polje može prihvatiti javni ili privatni ključ]",
		"vanitylabelnote2": "[NAPOMENA: ovo polje može prihvatiti javni ili privatni ključ]",
		"vanitylabelradioadd": "Dodaj (Add)",
		"vanitylabelradiomultiply": "Umnoži (Multiply)",
		"vanitycalc": "Izračunaj Vanity novčanik",
		"vanitylabelbitcoinaddress": "Bitcoin adresa Vanity:",
		"vanitylabelnotesbitcoinaddress": "Gore je navedena vaša nova adresa koja bi trebala sadržavati vaš željeni prefiks.",
		"vanitylabelpublickeyhex": "Vanity javni ključ (HEX):",
		"vanitylabelnotespublickeyhex": "Gore je naveden vaš javni ključ u hexadecimalnom formatu.",
		"vanitylabelprivatekey": "Vanity privatni ključ (WIF):",
		"vanitylabelnotesprivatekey": "Gore je naveden privatni ključ koji možete uvesti u vaš novčanik.",

		// split wallet html
		"splitlabelthreshold": "Minimalni broj podjela potrebnih za spajanje: ",
		"splitlabelshares": "Broj podjela (share-ova): ",
		"splitview": "Generiraj",
		"combinelabelentershares": "Unesite dostupne podjele (odjeljene praznim space znakom)",
		"combineview": "Spoji podjele",
		"combinelabelprivatekey": "Spojeni privatni ključ",

		// detail wallet html
		"detaillabelenterprivatekey": "Unesite privatni ključ:",
		"detailkeyformats": "Poržani formati: WIF, WIFC, HEX, B64, B6, MINI, BIP38",
		"detailview": "Prikaži detalje",
		"detailprint": "Ispis",
		"detaillabelnote1": "",
		"detaillabelnote2": "",
		"detaillabelbitcoinaddress": "Bitcoin adresa:",
		"detaillabelbitcoinaddresscomp": "Komprimirana bitcoin adresa:",
		"detaillabelpublickey": "Javni ključ (130 znakova [0-9A-F]):",
		"detaillabelpublickeycomp": "Komprimirani javni ključ (66 znakova [0-9A-F]):",
		"detaillabelprivwif": "Privatni ključ (WIF)  <br />51 znak base58, počinje znakom",
		"detaillabelprivwifcomp": "Komprimirani privatni ključ (WIF) <br />52 znaka base58, počinje znakovima",
		"detailcompwifprefix": "'K' ili 'L'",
		"detaillabelprivhex": "Privatni ključ u hexadecimalnom formatu (64 znaka [0-9A-F]):",
		"detaillabelprivb64": "Privatni ključ u base64 formatu (44 znaka):",
		"detaillabelprivmini": "Privatni ključ u mini formatu (22, 26 ili 30 znakaova, počinje znakom 'S'):",
		"detaillabelpassphrase": "Unesite BIP38 pristupni izraz (passphrase):",
		"detailbip38decryptbutton": "Dekriptiraj",
		"detailbip38encryptbutton": "Enkriptiraj BIP38",
		"detaillabelq1": "Kako napraviti novčanik koristeći kockicu za igru? Što je to B6?",
		"detaila1": "Važna stvar kod kreiranja Bitcoin novčanika je osigurati da nasumični brojevi koji se koriste za kreiranje novčanika budu zbilja nasumični. Fizička nasumičnost je bolja od one pseudo-nasumične generirane na računalu. Najjednostavniji način fizičke nasumičnosti je bacanje kockice za igru (Yamb). Za kreiranje Bitcoin novčanika, potrebna nam je jedna šesterostrana kockica za igru  koju ćemo bacati 99 puta. Svako bacanje je potrebno zabilježiti. Kada zabilježavate, koristeći sljedeća pravila: 1=1, 2=2, 3=3, 4=4, 5=5, 6=0. S ovime će te dobiti veliki nasumični broj s bazom 6 (B6 format). Tada unesite vaš privatni ključ, od 99 znaka s bazom 6 koji ste dobili bacanjem kockice, u gornje tekstualno polje i kliknite na Prikaži detalje. Tada će vam se prikazati detalji vašeg novčanika koji odgovara privatnom ključu generiranog bacanjem kockica. Također je dobro zabilježiti i napraviti sigurnosnu kopiju vašeg privatnog ključa u WIF formatu jer je u široj uporabi nego base6 ključ."
	};
})(ninja.translator);